# Generated by Django 5.2.1 on 2025-05-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='fine',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
