# Generated by Django 5.2.1 on 2025-05-19 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_quantity'),
        ('loans', '0002_loan_fine'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_physical',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='fine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
