# Generated by Django 5.2.1 on 2025-05-19 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_quantity'),
        ('loans', '0003_loan_is_physical_alter_loan_book_alter_loan_fine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='books.book'),
        ),
    ]
