# Generated by Django 5.2.1 on 2025-06-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_cleanup_days', models.PositiveIntegerField(default=30, help_text='Nombre de jours avant suppression des notifications supprimées')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, help_text='Seuil de stock minimum pour alerte de réapprovisionnement')),
                ('loan_warning_days', models.PositiveIntegerField(default=2, help_text='Jours avant la date de retour pour alerte de retour proche')),
                ('loan_overdue_days', models.PositiveIntegerField(default=0, help_text='Jours après la date de retour pour alerte de retard')),
                ('max_loans_per_user', models.PositiveIntegerField(default=3, help_text='Nombre maximum de prêts simultanés par utilisateur')),
                ('loan_duration', models.PositiveIntegerField(default=14, help_text='Durée standard d’un prêt en jours')),
                ('critical_stock_threshold', models.PositiveIntegerField(default=1, help_text='Seuil critique pour alerte de stock urgent')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres du système',
                'verbose_name_plural': 'Paramètres du système',
            },
        ),
    ]
