# Generated by Django 5.2.1 on 2025-05-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_cleanup_days', models.PositiveIntegerField(default=30, help_text='Nombre de jours avant suppression des notifications supprimées')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres du système',
                'verbose_name_plural': 'Paramètres du système',
            },
        ),
    ]
