# Generated by Django 5.2.1 on 2025-05-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='loan_overdue_days',
            field=models.PositiveIntegerField(default=0, help_text='Jours après la date de retour pour alerte de retard'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='loan_warning_days',
            field=models.PositiveIntegerField(default=2, help_text='Jours avant la date de retour pour alerte de retour proche'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Seuil de stock minimum pour alerte de réapprovisionnement'),
        ),
    ]
