# Generated by Django 5.2.1 on 2025-06-24 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='critical_stock_threshold',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='loan_duration',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='loan_overdue_days',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='loan_warning_days',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='low_stock_threshold',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='max_loans_per_user',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='notification_cleanup_days',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='notifications_enabled',
            field=models.BooleanField(default=True, help_text='Activer/Désactiver les notifications'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Numéro de téléphone de l'utilisateur", max_length=15, null=True),
        ),
    ]
