# Generated by Django 5.2.1 on 2025-06-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_remove_systemsettings_critical_stock_threshold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='notifications_enabled',
            field=models.BooleanField(default=True, help_text='Activer/Désactiver les notifications globales'),
        ),
    ]
