# Generated by Django 5.2.1 on 2025-05-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_systemsettings_loan_overdue_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='critical_stock_threshold',
            field=models.PositiveIntegerField(default=1, help_text='Seuil critique pour alerte de stock urgent'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='loan_duration',
            field=models.PositiveIntegerField(default=14, help_text='Durée standard d’un prêt en jours'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='max_loans_per_user',
            field=models.PositiveIntegerField(default=3, help_text='Nombre maximum de prêts simultanés par utilisateur'),
        ),
    ]
