# Generated by Django 5.2 on 2025-05-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='file_url',
        ),
        migrations.AddField(
            model_name='book',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='ebooks/'),
        ),
    ]
