# Generated by Django 5.2 on 2025-05-11 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_file_url_book_file_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='file_upload',
            new_name='ebook_file',
        ),
    ]
