# Generated by Django 5.2.1 on 2025-06-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='academic_level',
            field=models.CharField(blank=True, choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('N/A', 'Non applicable')], max_length=20, null=True),
        ),
    ]
