# Generated by Django 5.2.1 on 2025-06-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('info-new', 'Nouveau document'), ('info-update', 'Document modifié'), ('warning-delete', 'Document supprimé'), ('info-user', 'Nouvel utilisateur'), ('warning-access', 'Demande d’accès'), ('info-system', 'Système'), ('danger-file', 'Problème de fichier')], max_length=20),
        ),
    ]
