# Generated by Django 5.2.1 on 2025-05-22 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_deleted',
        ),
    ]
