# Generated by Django 5.2.1 on 2025-06-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50)),
                ('loan_date', models.DateTimeField()),
                ('is_physical', models.BooleanField()),
            ],
            options={
                'db_table': 'loans_history',
                'ordering': ['-loan_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('fine', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_physical', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'loans_loan',
                'ordering': ['-loan_date'],
                'managed': False,
            },
        ),
    ]
