# Generated by Django 5.2.1 on 2025-05-30 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_readinghistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadingHistory',
        ),
    ]
