# Generated by Django 5.2.1 on 2025-06-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_delete_readinghistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50)),
                ('loan_date', models.DateTimeField()),
                ('is_physical', models.BooleanField()),
            ],
            options={
                'db_table': 'loans_history',
                'ordering': ['-loan_date'],
                'managed': False,
            },
        ),
    ]
