# Generated by Django 5.2.1 on 2025-06-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='department',
            field=models.CharField(blank=True, choices=[('Chimie appliquée', 'Chimie appliquée'), ('Géosciences', 'Géosciences'), ('Physique appliquée', 'Physique appliquée'), ('ROSE', 'ROSE'), ('SBAA', 'SBAA'), ('SBM', 'SBM'), ('TBM', 'TBM'), ('TIC', 'TIC')], max_length=50, null=True),
        ),
    ]
