# Generated by Django 5.2.1 on 2025-06-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_document_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, choices=[('informatique', 'Informatique'), ('physique', 'Physique'), ('chimie', 'Chimie'), ('mathematiques', 'Mathématiques'), ('sciences', 'Sciences'), ('biotechnologie', 'Biotechnologie'), ('agriculture', 'Agriculture'), ('elevage', 'Élevage'), ('technologie', 'Technologie'), ('autre', 'Autre')], max_length=50),
        ),
    ]
