# Generated by Django 5.2.1 on 2025-06-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('document_type', models.CharField(choices=[('ebook', 'E-book'), ('exam', 'Épreuve'), ('course', 'Support de cours'), ('td', 'Fiche de TD'), ('article', 'Article')], max_length=20)),
                ('academic_level', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3'), ('M1', 'Master 1'), ('M2', 'Master 2'), ('D', 'Doctorat'), ('N/A', 'Non applicable')], default='N/A', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['title'],
            },
        ),
    ]
