# Generated by Django 5.2.1 on 2025-06-04 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_ebook',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
