# Generated by Django 5.2.1 on 2025-06-19 03:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_book_ebook_file_alter_document_academic_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'verbose_name': 'E-book', 'verbose_name_plural': 'E-books'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_borrowed',
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_ebook',
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_physical',
        ),
        migrations.RemoveField(
            model_name='book',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='book',
            name='ebook_file',
            field=models.FileField(upload_to='ebooks/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
