# Generated by Django 5.2.1 on 2025-07-03 09:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_identifier', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=20)),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('info-new', 'Nouveau document'), ('info-update', 'Document modifié'), ('warning-delete', 'Document supprimé'), ('info-user', 'Nouvel utilisateur'), ('warning-access', 'Demande d’accès'), ('info-system', 'Système'), ('danger-file', 'Problème de fichier')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('unique_identifier', models.CharField(default='', editable=False, max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
